services:
    wordpress:
        image: wordpress:beta-6.9
        restart: always
        ports:
            - 8080:80
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: exampleuser
            WORDPRESS_DB_PASSWORD: examplepass
            WORDPRESS_DB_NAME: exampledb
        volumes:
            - wordpress:/var/www/html
            - ./fair-calendar-button:/var/www/html/wp-content/plugins/fair-calendar-button
            - ./fair-payment:/var/www/html/wp-content/plugins/fair-payment
            - ./fair-registration:/var/www/html/wp-content/plugins/fair-registration
            - ./fair-schedule-blocks:/var/www/html/wp-content/plugins/fair-schedule-blocks
            - ./fair-timetable:/var/www/html/wp-content/plugins/fair-timetable
            - ./fair-membership:/var/www/html/wp-content/plugins/fair-membership
            - ./fair-events:/var/www/html/wp-content/plugins/fair-events
            - ./fair-rsvp:/var/www/html/wp-content/plugins/fair-rsvp
            - ./fair-user-import:/var/www/html/wp-content/plugins/fair-user-import

    db:
        image: mysql:8.0
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: exampledb
            MYSQL_USER: exampleuser
            MYSQL_PASSWORD: examplepass
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
        volumes:
            - db:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '8081:80'
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: examplepass
        depends_on:
            - db

    wpcli:
        image: wordpress:cli
        profiles: ['cli'] # This prevents it from starting by default
        command: tail -f /dev/null # Keeps container running
        volumes:
            - wordpress:/var/www/html
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: exampleuser
            WORDPRESS_DB_PASSWORD: examplepass
            WORDPRESS_DB_NAME: exampledb
        depends_on:
            - db
            - wordpress

    fair-event-plugins.com:
        image: php:8.2-apache
        ports:
            - '8082:80'
        volumes:
            - ./fair-event-plugins.com:/var/www/html

    wordpress-php74:
        image: wordpress:6.1.1-php7.4
        platform: linux/amd64
        restart: always
        profiles: ['php74']
        ports:
            - 8083:80
        environment:
            WORDPRESS_DB_HOST: db-php74
            WORDPRESS_DB_USER: exampleuser
            WORDPRESS_DB_PASSWORD: examplepass
            WORDPRESS_DB_NAME: exampledb
        volumes:
            - wordpress-php74:/var/www/html
            - ./fair-calendar-button:/var/www/html/wp-content/plugins/fair-calendar-button
            - ./fair-payment:/var/www/html/wp-content/plugins/fair-payment
            - ./fair-registration:/var/www/html/wp-content/plugins/fair-registration
            - ./fair-schedule-blocks:/var/www/html/wp-content/plugins/fair-schedule-blocks
            - ./fair-timetable:/var/www/html/wp-content/plugins/fair-timetable
            - ./fair-membership:/var/www/html/wp-content/plugins/fair-membership
            - ./fair-events:/var/www/html/wp-content/plugins/fair-events
            - ./fair-rsvp:/var/www/html/wp-content/plugins/fair-rsvp
        depends_on:
            - db-php74

    db-php74:
        image: mysql:5.7
        platform: linux/amd64
        restart: always
        profiles: ['php74']
        ports:
            - 3307:3306
        environment:
            MYSQL_DATABASE: exampledb
            MYSQL_USER: exampleuser
            MYSQL_PASSWORD: examplepass
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
        volumes:
            - db-php74:/var/lib/mysql

    wordpress-wp63:
        image: wordpress:6.3.2-php8.2
        platform: linux/amd64
        restart: always
        profiles: ['wp63']
        ports:
            - 8084:80
        environment:
            WORDPRESS_DB_HOST: db-wp63
            WORDPRESS_DB_USER: exampleuser
            WORDPRESS_DB_PASSWORD: examplepass
            WORDPRESS_DB_NAME: exampledb
        volumes:
            - wordpress-wp63:/var/www/html
            - ./fair-calendar-button:/var/www/html/wp-content/plugins/fair-calendar-button
            - ./fair-payment:/var/www/html/wp-content/plugins/fair-payment
            - ./fair-registration:/var/www/html/wp-content/plugins/fair-registration
            - ./fair-schedule-blocks:/var/www/html/wp-content/plugins/fair-schedule-blocks
            - ./fair-timetable:/var/www/html/wp-content/plugins/fair-timetable
            - ./fair-membership:/var/www/html/wp-content/plugins/fair-membership
            - ./fair-events:/var/www/html/wp-content/plugins/fair-events
            - ./fair-rsvp:/var/www/html/wp-content/plugins/fair-rsvp
        depends_on:
            - db-wp63

    db-wp63:
        image: mysql:8.0
        restart: always
        profiles: ['wp63']
        ports:
            - 3308:3306
        environment:
            MYSQL_DATABASE: exampledb
            MYSQL_USER: exampleuser
            MYSQL_PASSWORD: examplepass
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
        volumes:
            - db-wp63:/var/lib/mysql

    wordpress-wp67:
        image: wordpress:6.7-php8.3
        platform: linux/amd64
        restart: always
        profiles: ['wp67']
        ports:
            - 8085:80
        environment:
            WORDPRESS_DB_HOST: db-wp67
            WORDPRESS_DB_USER: exampleuser
            WORDPRESS_DB_PASSWORD: examplepass
            WORDPRESS_DB_NAME: exampledb
        volumes:
            - wordpress-wp67:/var/www/html
            - ./fair-calendar-button:/var/www/html/wp-content/plugins/fair-calendar-button
            - ./fair-payment:/var/www/html/wp-content/plugins/fair-payment
            - ./fair-registration:/var/www/html/wp-content/plugins/fair-registration
            - ./fair-schedule-blocks:/var/www/html/wp-content/plugins/fair-schedule-blocks
            - ./fair-timetable:/var/www/html/wp-content/plugins/fair-timetable
            - ./fair-membership:/var/www/html/wp-content/plugins/fair-membership
            - ./fair-events:/var/www/html/wp-content/plugins/fair-events
            - ./fair-rsvp:/var/www/html/wp-content/plugins/fair-rsvp
        depends_on:
            - db-wp67

    db-wp67:
        image: mysql:8.0
        restart: always
        profiles: ['wp67']
        ports:
            - 3309:3306
        environment:
            MYSQL_DATABASE: exampledb
            MYSQL_USER: exampleuser
            MYSQL_PASSWORD: examplepass
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
        volumes:
            - db-wp67:/var/lib/mysql

volumes:
    wordpress:
    db:
    wordpress-php74:
    db-php74:
    wordpress-wp63:
    db-wp63:
    wordpress-wp67:
    db-wp67:
